---
- name: 'Ensure rust directory'
  file:
    path: '{{ devenv_root }}/rust'
    state: 'directory'
- name: 'Ensure rustup-init directory'
  file:
    path: '{{ devenv_root }}/rust/init'
    state: 'directory'
- name: 'Download rustup-init'
  get_url:
    url: 'https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init'
    dest: '{{ devenv_root }}/rust/init/rustup-init'
    mode: 0755
- name: 'Ensure rust envfile'
  copy:
    src: 'env.sh'
    dest: '{{ devenv_root }}/envs/01_rust.sh'
