---
- hosts: 'localhost'
  become: false
  vars_files:
    - 'vars.yaml'
    - 'hashes.yaml'
  roles:
    - 'awscli'
    - 'gcloud'
    - 'golang'
    - 'helm'
    - 'hugo'
    - 'istioctl'
    - 'kubectl'
    - 'kustomize'
    - 'nodejs'
    - 'restic'
    - 'terraform'
    - 'ytdl'
