---
- name: 'Ensure awscli directory'
  file:
    path: '{{ devenv_root }}/awscli'
    state: 'directory'
- name: 'Ensure awscli current directory'
  file:
    path: '{{ devenv_root }}/awscli/current'
    state: 'directory'
- name: 'Ensure awscli version directory'
  file:
    path: '{{ devenv_root }}/awscli/{{ devenv_awscli_version }}'
    state: 'directory'
- name: 'Download awscli'
  get_url:
    url: 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64-{{ devenv_awscli_version }}.zip'
    dest: '{{ devenv_root }}/awscli/{{ devenv_awscli_version }}_download.zip'
    checksum: 'sha256:{{ devenv_awscli_hash[devenv_awscli_version] }}'
- name: 'Unpack awscli'
  unarchive:
    src: '{{ devenv_root }}/awscli/{{ devenv_awscli_version }}_download.zip'
    dest: '{{ devenv_root }}/awscli/{{devenv_awscli_version }}'
- name: 'Ensure awscli envfile'
  copy:
    src: 'env.sh'
    dest: '{{ devenv_root }}/envs/01_awscli.sh'
- name: 'Ensure awscli executable aws'
  file:
    src: '../{{ devenv_awscli_version }}/aws/dist/aws'
    path: '{{ devenv_root }}/awscli/current/aws'
    state: 'link'
- name: 'Ensure awscli executable aws_completer'
  file:
    src: '../{{ devenv_awscli_version }}/aws/dist/aws_completer'
    path: '{{ devenv_root }}/awscli/current/aws_completer'
    state: 'link'
