---
- name: 'Ensure protoc directory'
  file:
    path: '{{ devenv_root }}/protoc'
    state: 'directory'
- name: 'Ensure protoc version directory'
  file:
    path: '{{ devenv_root }}/protoc/{{ devenv_protoc_version }}'
    state: 'directory'
- name: 'Download protoc'
  get_url:
    url: 'https://github.com/protocolbuffers/protobuf/releases/download/v{{ devenv_protoc_version }}/protoc-{{ devenv_protoc_version }}-linux-x86_64.zip'
    dest: '{{ devenv_root }}/protoc/{{ devenv_protoc_version }}_download.zip'
- name: 'Unpack protoc'
  unarchive:
    src: '{{ devenv_root }}/protoc/{{ devenv_protoc_version }}_download.zip'
    dest: '{{ devenv_root }}/protoc/{{ devenv_protoc_version }}'
- name: 'Ensure protoc envfile'
  copy:
    src: 'env.sh'
    dest: '{{ devenv_root }}/envs/01_protoc.sh'
- name: 'Update current protoc'
  file:
    src: '{{ devenv_protoc_version }}'
    path: '{{ devenv_root }}/protoc/current'
    state: 'link'
