---
- name: 'Ensure packer directory'
  file:
    path: '{{ devenv_root }}/packer'
    state: 'directory'
- name: 'Ensure packer version directory'
  file:
    path: '{{ devenv_root }}/packer/{{ devenv_packer_version }}'
    state: 'directory'
- name: 'Download packer'
  get_url:
    url: 'https://releases.hashicorp.com/packer/{{ devenv_packer_version }}/packer_{{ devenv_packer_version }}_linux_amd64.zip'
    dest: '{{ devenv_root }}/packer/{{ devenv_packer_version }}_download.zip'
    checksum: 'sha256:{{ devenv_packer_hash[devenv_packer_version] }}'
- name: 'Unpack packer'
  unarchive:
    src: '{{ devenv_root }}/packer/{{ devenv_packer_version }}_download.zip'
    dest: '{{ devenv_root }}/packer/{{ devenv_packer_version }}'
- name: 'Ensure packer envfile'
  copy:
    src: 'env.sh'
    dest: '{{ devenv_root }}/envs/01_packer.sh'
- name: 'Update current packer'
  file:
    src: '{{ devenv_packer_version }}'
    path: '{{ devenv_root }}/packer/current'
    state: 'link'
