---
- name: 'Ensure ngrok directory'
  file:
    path: '{{ devenv_root }}/ngrok'
    state: 'directory'
- name: 'Ensure ngrok bin directory'
  file:
    path: '{{ devenv_root }}/ngrok/bin'
    state: 'directory'
- name: 'Download ngrok'
  get_url:
    url: 'https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip'
    dest: '{{ devenv_root }}/ngrok/ngrok_download.zip'
- name: 'Unpack ngrok'
  unarchive:
    src: '{{ devenv_root }}/ngrok/ngrok_download.zip'
    dest: '{{ devenv_root }}/ngrok/bin'
- name: 'Ensure ngrok envfile'
  copy:
    src: 'env.sh'
    dest: '{{ devenv_root }}/envs/01_ngrok.sh'
