---
- name: 'Ensure gcloud directory'
  file:
    path: '{{ devenv_root }}/gcloud'
    state: 'directory'
- name: 'Ensure gcloud version directory'
  file:
    path: '{{ devenv_root }}/gcloud/{{ devenv_gcloud_version }}'
    state: 'directory'
- name: 'Download gcloud'
  get_url:
    url: 'https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-{{ devenv_gcloud_version }}-linux-x86_64.tar.gz'
    dest: '{{ devenv_root }}/gcloud/{{ devenv_gcloud_version }}_download.zip'
    checksum: 'sha256:{{ devenv_gcloud_hash[devenv_gcloud_version] }}'
- name: 'Unpack gcloud'
  unarchive:
    src: '{{ devenv_root }}/gcloud/{{ devenv_gcloud_version }}_download.zip'
    dest: '{{ devenv_root }}/gcloud/{{ devenv_gcloud_version }}'
    extra_opts: ['--strip-components', '1']
- name: 'Ensure gcloud envfile'
  copy:
    src: 'env.sh'
    dest: '{{ devenv_root }}/envs/01_gcloud.sh'
- name: 'Update current gcloud'
  file:
    src: '{{ devenv_gcloud_version }}'
    path: '{{ devenv_root }}/gcloud/current'
    state: 'link'
