name: Test
on:
  push:
    branches:
      - master

jobs:
  ansible:
    name: Ansible
    runs-on: ubuntu-20.04
    env: {}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ansible Playbook
        run: ansible-playbook -v main.yaml
      - name: Test
        env:
          DEVENV_DEBUG: '1'
        run: bash -c 'source .devenv/activate'
